version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak-authentication
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloak-database
    ports:
      - 8080:8080
    networks:
      - mynetwork

  keycloak-database:
    image: postgres:15
    container_name: keycloak-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:
    image: keycloak-jwt # local image
    container_name: backend-service
    ports:
      - 2007:2007
    depends_on:
      - keycloak
      - keycloak-database
    networks:
      - mynetwork
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://keycloak-database:5432/keycloak
      SPRING_DATASOURCE_USERNAME: keycloak
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data:

networks:
  mynetwork:
